spring:
  datasource:
    url: dbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa: org.hibernate.dialect.H2Dialect
      database-platform
#  r2dbc:
#    url: r2dbc:h2:mem:///testdb
#    driver: io.r2dbc.h2.H2ConnectionConfiguration
#    username: sa
#    password:
#external:
#  api:
#    base-url: https://api.example.com

